title: Site

pages:
  template:
    - default
    - blog

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea

  dateformat:
    label: Date Format
    type: text
    placeholder: d/m/Y
    help: "PHP date format: http://php.net/manual/en/function.date.php"
