title: Site

pages:
  template:
    - default
    - blog

fields:

  meta:
    label: Meta
    type: headline

  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  brand:
    label: Brand
    type: headline

  favicon:
    label: Favicon
    type: image
    help: min 32x32px

  touch_icon:
    label: Touch Icon
    type: image
    help: min 192x192px

  navigation:
    label: Navigation
    type: headline

  navigation_main:
    label: Main Navigation
    type: checkboxes
    options: query
    query: pages

  footer:
    label: Footer
    type: headline

  copyright:
    label: Copyright
    type:  textarea

  blog:
    label: Blog
    type: headline

  dateformat:
    label: Date Format
    type: text
    placeholder: d/m/Y
    help: "PHP date format: http://php.net/manual/en/function.date.php"
