title: Site

pages:
  template:
    - blog
    - contact
    - default

fields:

  meta:
    extends: meta
    fields:
      favicon:
        label: Favicon
        type:  image
        help: Image must be at least 32 x 32 pixels
        translate: false

      touch_icon:
        label: Touch Icon
        type:  image
        help: Image must be at least 192 x 192 pixels
        translate: false

  brand:
    label: Brand
    type: headline

  logo:
    label: Logo
    type: image

  navigation:
    label: Navigation
    type: headline

  navigation_main:
    label: Main Navigation
    type: checkboxes
    options: query
    query: pages

  footer:
    label: Footer
    type: headline

  copyright:
    label: Copyright
    type:  textarea

  blog:
    label: Blog
    type: headline

  dateformat:
    label: Date Format
    type: text
    placeholder: d/m/Y
    help: "PHP date format: http://php.net/manual/en/function.date.php"

  blog_comments_open:
    label: Comments
    type: checkbox
    text: Enable Comments
